### PR TITLE
Adding tests to conda build

### PR DESCRIPTION
**Pull request by aladinoster**
Adding tests conda build + channel order

### CODE REVIEW

**Comment by floriangc** [comment]
I tried build locally the package and I have the following error:
```
==================================== ERRORS ====================================
___________________ ERROR collecting tests/test_commands.py ____________________
ImportError while importing test module '$SRC_DIR/tests/test_commands.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_commands.py:17: in <module>
    from symupy.api.commands import NoCommand
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.9/site-packages/symupy/api/commands/__init__.py:1: in <module>
    from .nocommand import NoCommand
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.9/site-packages/symupy/api/commands/nocommand.py:15: in <module>
    from symupy.utils.metaclass.command import AbsCommand
E   ModuleNotFoundError: No module named 'symupy.utils.metaclass'
------------------------------- Captured stdout --------------------------------
Successful import of symupy
=========================== short test summary info ============================
ERROR tests/test_commands.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
============================== 1 error in 21.06s ===============================
```

Is `metaclass` a deprecated module ? (`ModuleNotFoundError: No module named 'symupy.utils.metaclass'`)

**Comment by aladinoster** [comment]
Regularly these files are on `master` although unused since december check here → 083144a74f2d8cda5eaced9d30586a7d2c1b3a0e

Maybe rebasing to get the latest version from `master` to `dev`?

**Review by floriangc — APPROVED** [review]
Yes, we can merge/rebase `master` into `dev` and then merge this if its okay for you.

**Comment by aladinoster** [comment]
I think, this should work, I'm merging this into `dev`. Later when publishing a new version we will merge into `master` as a regular release. This should run tests when building. I'm currently on some tests that need to be fixed. Regularly the rebasing should happen locally.

**Pull request merged**
